project_name: accuknoxcli

builds:
  - binary: knoxctl
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

signs:
  - cmd: cosign
    certificate: '${artifact}.cert'
    args:
      - sign-blob
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
      - --yes
    artifacts: all
    output: true