kubearmor-addr: {{.KubeArmorURL}}

relay-server-addr: {{.RelayServerURL}}

{{- if trimPrefix "v" .ReleaseVersion | semverCompare ">0.9.1" }}
node-state-refresh: {{.NodeStateRefreshTime}}
{{- end }}

{{- if .TlsEnabled }}
tls: {{.TlsEnabled}}
policy-topic: {{.PoliciesTopic}}
state-topic: {{.StateEventTopic}}
alert-topic: {{.AlertsTopic}}
logs-topic: {{.LogsTopic}}
kmux-config-policy: /opt/kubearmor-vm-adapter/policies-kmux-config.yaml
kmux-config-state: /opt/kubearmor-vm-adapter/state-kmux-config.yaml
kmux-config-alerts: /opt/kubearmor-vm-adapter/alerts-kmux-config.yaml
kmux-config-logs: /opt/kubearmor-vm-adapter/logs-kmux-config.yaml
{{- else }}
sia-addr: {{.SIAAddr}}

pea-addr: {{.PEAAddr}}

harden-addr: {{.HardenAddr}}
{{- end }}


{{- if .SpireEnabled }}
spire: {{.SpireEnabled}}
spire-agent: "unix:///var/run/spire/agent.sock"
spire-cert: {{.SpireCert}}
{{- end }}