kubearmor-addr: {{.KubeArmorURL}}

relay-server-addr: {{.RelayServerURL}}

{{- if .TlsEnabled }}
tls: {{.TlsEnabled}}
policy-topic: {{.PoliciesTopic}}
state-topic: {{.StateEventTopic}}
alert-topic: {{.AlertsTopic}}
logs-topic: {{.LogsTopic}}
kmux-config-policy: {{.PoliciesKmuxConfig}}
kmux-config-state: {{.StateKmuxConfig}}
kmux-config-alerts: {{.AlertsKmuxConfig}}
kmux-config-logs: {{.LogsKmuxConfig}}
{{- else }}
sia-addr: {{.SIAAddr}}

pea-addr: {{.PEAAddr}}

harden-addr: {{.HardenAddr}}
{{- end }}