kmux:
  source:
    stream: rabbitmq

rabbitmq:
  server: {{.RMQServer}}
  username: {{.RMQUsername}}
  password: {{.RMQPassword}}
  exchange:
    name: {{.ExchangeName}}
    type: {{.ExchangeType}} # exchange type
    durable: true
    auto-delete: true
  queue:
    auto-delete: true
    durable: {{.QueueDurability}}
    name: {{.QueueName}}
  consumer-tag: {{.ConsumerTag}}  
  debug: false
  tls: 
    enabled: {{.TlsEnabled}}
    cert-file: {{.TlsCertFile}}
    skip-verify: false
  connection-name: {{.ConnectionName}}