
kmux:
  sink:
    stream: rabbitmq
  source:
    stream: rabbitmq
rabbitmq:
  username: {{.RMQUsername}}
  password: {{.RMQPassword}}
  exchange:
    auto-delete: true
    durable: true
    name: agents
    type: direct
  queue:
    auto-delete: true
    durable: true
    name: ""
  server: {{.RMQServer}}
  tls: 
    enabled: {{.TlsEnabled}}
    cert-file: "/opt/cert/encoded.pem"
    skip-verify: false
