name: accuknox-rra
services:
  rra:
    profiles:
      - "accuknox-agents"
    image: "{{.RRAImage}}"
    container_name: accuknox-rra
    restart: always
    pid: "host" 
    network_mode: "host" 
    privileged: true
    hostname: "{{.Hostname}}"
    volumes:
      - /tmp:/host/tmp
      - /:/host:ro
    environment:
      - CRON_SCHEDULE={{.Schedule}}
      - PROFILE={{.Profile}}
      - BENCHMARK={{.Benchmark}}
      - AUTH_TOKEN={{.AuthToken}}
      - URL={{.Url}}
      - TENANT_ID={{.TenantID}}
      - CLUSTER_NAME={{.ClusterName}}
      - CLUSTER_ID={{.ClusterID}}
      - LABEL={{.Label}}
    entrypoint: ["/rra/rra-cronjob.sh"]   
