version: '3.8'
services:
  kubearmor-init:
    profiles:
      - "kubearmor-only"
      - "kubearmor"
    container_name: kubearmor-init
    image: {{.KubeArmorInitImage}}
    labels:
      app: kubearmor-init
    volumes:
      - "/tmp:/opt/kubearmor/BPF:rw"
      - "/lib/modules:/lib/modules:ro"
      - "/sys/fs/bpf:/sys/fs/bpf:ro"
      - "/sys/kernel/security:/sys/kernel/security:ro"
      - "/sys/kernel/debug:/sys/kernel/debug:ro"
      - "/media/root/etc/os-release:/media/root/etc/os-release:ro"
    restart: on-failure:4
    privileged: true
    networks:
      accuknox-net:
        aliases:
          - kubearmor-init

  kubearmor:
    profiles:
      - "kubearmor-only"
      - "kubearmor"
    depends_on:
      kubearmor-init:
        condition: service_completed_successfully
    hostname: {{.Hostname}}
    container_name: kubearmor
    image: "{{.KubeArmorImage}}"
    command:
      - "-k8s=false"
      - "-enableKubeArmorPolicy"
      - "-enableKubeArmorHostPolicy"
      - "-hostVisibility=\"process,network\""
      - "-criSocket=unix:///var/run/docker.sock"
      - "-enableKubeArmorStateAgent"
    labels:
      app: kubearmor
    volumes:
      - "/tmp:/opt/kubearmor/BPF:rw"
      - "/sys/fs/bpf:/sys/fs/bpf"
      - "/sys/kernel/security:/sys/kernel/security"
      - "/sys/kernel/debug:/sys/kernel/debug"
      - "/etc/apparmor.d:/etc/apparmor.d"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/run/docker:/run/docker"
      - "/var/lib/docker:/var/lib/docker"
    restart: on-failure:4
    ports:
      - "{{.KubeArmorPort}}:32767"
    networks:
      accuknox-net:
        aliases:
          - kubearmor
    pid: "host"
    privileged: true

  kubearmor-vm-adapter:
    profiles:
      - "kubearmor-only"
      - "kubearmor"
    depends_on:
      - kubearmor
    container_name: kubearmor-vm-adapter
    image: "{{.KubeArmorVMAdapterImage}}"
    command:
      - "--kubearmor-addr={{.KubeArmorURL}}"
      - "--relay-server-addr={{.RelayServerURL}}"
      - "--sia-addr={{.SIAAddr}}"
      - "--pea-addr={{.PEAAddr}}"
    volumes:
      - "{{.ConfigPath}}:/opt"
    labels:
      app: kubearmor-vm-adapter
    restart: on-failure:4
    network_mode: "host"

networks:
  accuknox-net: {}
