kmux:
  sink:
    stream: rabbitmq
  source:
    stream: rabbitmq

rabbitmq:
  server: {{.RMQServer}}
  username: {{.RMQUsername}}
  password: {{.RMQPassword}}
  exchange:
    name: "agents"
    type: "direct"
    durable: true
    auto-delete: true
  queue:
    name: ""
    durable: true
    auto-delete: true
  consumer-tag: {{.ConsumerTag}}
  tls: 
    enabled: {{.TlsEnabled}}
    cert-file: "/opt/cert/encoded.pem"
    skip-verify: false