kmux:
  sink:
    stream: {{.StreamName}}
  source:
    stream: rabbitmq  
  security: spire

knox-gateway:
  server: {{.ServerURL}}

spire:
  spiffeID:
    format: "spiffe://<domainName>/<WSID>/<ClusterID>/<componentName>"
  
  suffixSkipSet:
    - ".sock"
    - ".socket"

rabbitmq:
  server: {{.RMQServer}}
  exchange:
    name: "dev2" 
    type: "direct"
    durable: true
    auto-delete: true
  queue:
    name: ""
    durable: true
    auto-delete: true
  debug: false
