kmux:
  sink:
    stream: {{.StreamName}}

{{- if trimPrefix "v" .ReleaseVersion | semverCompare ">=0.3.0" }}
  # kmux SPIRE APIs were added after 0.3.0
  security: spire
{{- end }}

knox-gateway:
  server: {{.ServerURL}}

spire:
  spiffeID:
    format: "spiffe://<domainName>/<WSID>/<ClusterID>/<componentName>"
{{- if trimPrefix "v" .ReleaseVersion | semverCompare ">=0.3.0" }}
  # kmux SPIRE APIs were added after 0.3.0
  suffixSkipSet:
    - ".sock"
    - ".socket"
{{- end }}
