kmux:
  sink:
    stream: {{.StreamName}}
  security: spire

knox-gateway:
  server: {{.ServerURL}}

spire:
  spiffeID:
    format: "spiffe://<domainName>/<WSID>/<ClusterID>/<componentName>"
  suffixSkipSet:
    - ".sock"
    - ".socket"
