kmux:
  sink:
    stream: rabbitmq

rabbitmq:
  server: {{.RMQServer}}
  username: {{.RMQUsername}}
  password: {{.RMQPassword}}
  exchange:
    name: {{.ExchangeName}}
    type: {{.ExchangeType}} # exchange type
    durable: true
    auto-delete: true
  queue:
    auto-delete: true
    durable: {{.QueueDurability}}
  debug: false
  tls: 
    enabled: {{.TlsEnabled}}
    {{- if .UseCaFile }}
    ca-file: {{.TlsCertFile}}
    {{- else }}
    cert-file: {{.TlsCertFile}}
    {{- end }}
    skip-verify: false
  connection-name: {{.ConnectionName}}