spire:
  enable: true
  agent: "unix:///var/run/spire/agent.sock"

{{- if trimPrefix "v" .ReleaseVersion | semverCompare "<0.5.0" }}
# if <v0.5.0 add kmux-topic prefix for pulsar
kmux-topic: shared-event

kmux-topic-prefix: persistent://accuknox/cluster-entity/
{{ else }}
kmux-topic: cluster-entity/shared-event
{{- end }}

kmux-vm-topic: vm-entity/shared-event
kmux-vm-topic-prefix: ""
kmux-vm-config: {{.KmuxConfigPath}}

heartbeat:
  interval: 5m

resource-refresh:
  interval: 5m

kmux-config-file: {{.KmuxConfigPath}}

state-agent:
  port: 32769

k8s:
  enable: false

tls:
  enabled: {{.TlsEnabled}}
  state-topic: {{.StateEventTopic}}

deployMode: "vm"