kmux:
  sink:
    stream: rabbitmq

rabbitmq:
  server: {{.RMQServer}}
  exchange:
    name: "dev2" # exchange name
    type: "direct" # exchange type
    durable: true
    auto-delete: true
  debug: false