watcher:
  kubearmor:
    enabled: true
    event-type:
      logs: true
      alerts: true
    relay:
      enabled: true
  {{- if .WorkerNode }}
      name: kubearmor
      url: {{.KubeArmorAddr}}
      port: {{.KubeArmorPort}}
  {{- else }}
      name: relay-1
      url: {{.RelayServerAddr}}
      port: {{.RelayServerPort}}
  {{- end }}
{{- if and .TlsEnabled (not .WorkerNode) }}
  rabbitmq:
    enabled: true
    logs-topic: {{.LogsTopic}}
    logs-kmux-config: {{.LogsKmuxConfig}}
    alerts-topic: {{.AlertsTopic}}
    alerts-kmux-config: {{.AlertsKmuxConfig}}
{{- end }}

summary-engine:
  kubearmor:
    enabled: true
    cron-interval: "0h05m00s"
    threshold: 10000
    file-aggregation: true
    exclude-events:
      operation:
        process: {{.ProcessOperation}}
        file: {{.FileOperation}}
        network: {{.NetworkOperation}}
    exclude-namespaces:
      kubearmor: true 
  topic:
    summary-event: {{.SummaryV2Topic}}
  kmux-config:
    summary-event: {{.SummaryKmuxConfig}}
  k8s:
    enable: false
  tls:
    enabled: {{.TlsEnabled}}
