app.yaml: |
  offloader:
    summary:
      enabled: "true"
      topic: "summary-v2"
    policy:
      enabled: "true"
      topic: "policy-v1"
      merge_policy: "false"
    server:
      enabled: "true"
      host: "0.0.0.0"
      port: "8090"

  # Database configurations
  database:
    driver: "sqlite"
    name: "accuknox.db"
    host: "localhost"
    port: "5432"
    schema: "cwpp"
    credentials: "local"
    secret: 
      path: "/knox/offloader/secrets"
      key:
        username: "postgres_user"
        password: "postgres_password"



kmux.yaml: |
  kmux:
    source:
      stream: "rabbitmq"
    sink:
      stream: "rabbitmq"
  rabbitmq:
    server: "localhost:5672"
    exchange:
      name: "dev2"
      type: "direct"
