name: PR Checks

on:
  pull_request_target:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:

  go-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "v1.20"

      - name: Setup GH Token
        env:
          GOPRIVATE: github.com/accuknox/*
          USER: accuknox-user
          TOKEN: ${{ secrets.AK_PAT_REPO_SCOPE }}
        run: |
          git config --global url."https://${USER}:${TOKEN}@github.com".insteadOf "https://github.com"
          go env -w GOPRIVATE=github.com/accuknox

      - name: Check gofmt
        run: make gofmt

      - name: Run Gosec Security Scanner
        run: make gosec

      - name: Run Revive Action by pulling pre-built imag
        uses: morphy2k/revive-action@v2
        with:
          path: "./..."

      - name: Run unit tests
        run: make test

      - name: Build knoxctl
        run: make