name: goreleaser

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/accuknox/*
      GH_ACCESS_TOKEN: ${{ secrets.AK_PAT_REPO_SCOPE }}
      GIT_KEY: ${{ secrets.GIT_KEY }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Install Cosign
        uses: sigstore/cosign-installer@main

      - name: Setup access for private go modules
        run: |
          sudo apt update -y
          sudo apt install -y make gcc musl-dev git
          mkdir ~/.ssh || true
          printf '[url "git@github.com:"] \n        insteadOf = https://github.com/' > ~/.gitconfig
          echo "${{ secrets.GIT_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          touch ~/.ssh/known_hosts 
          ssh-keyscan github.com >> ~/.ssh/known_hosts 
          export GOPRIVATE="github.com/accuknox"
          sudo cat ~/.gitconfig
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}