name: Release knoxctl

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  id-token: write

jobs:
  knoxctl-release:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/accuknox/*
      GH_ACCESS_TOKEN: ${{ secrets.AK_PAT_REPO_SCOPE }}
      GIT_KEY: ${{ secrets.GIT_KEY }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install Cosign
        uses: sigstore/cosign-installer@main

      - name: Setup access for private go modules
        env:
          GOPRIVATE: github.com/accuknox/*
          USER: accuknox-user
          TOKEN: ${{ secrets.AK_PAT_REPO_SCOPE }}
        run: |
          git config --global url."https://${USER}:${TOKEN}@github.com".insteadOf "https://github.com"
          

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch Tag Name
        id: get_tag
        run: echo "::set-output name=TAG_NAME::$(git describe --tags --abbrev=0)"

      - name: Checkout knoxctl-website Repository
        uses: actions/checkout@v3
        with:
          repository: accuknox/knoxctl-website
          token: ${{ secrets.AK_PAT_REPO_SCOPE }}
          path: knoxctl-website
          ref: main

      - name: Update latest version file 
        run: |
          echo "${{ steps.get_tag.outputs.TAG_NAME }}" > knoxctl-website/static/version/latest_version.txt
          cd knoxctl-website
          git config user.name "accuknox-user"
          git config user.email "devops.alerts@accuknox.com"
          git add static/version/latest_version.txt
          git commit -m "[knoxctl-ci-bot] Update latest version to ${{ steps.get_tag.outputs.TAG_NAME }}"
          git push origin main
      - name: Upload binaries to knoxctl-website
        run: |
          cp -r dist/* knoxctl-website/static/binaries/
          cd knoxctl-website
          git add static/binaries/
          git commit -m "[knoxctl-ci-bot] Add binaries for version ${{ steps.get_tag.outputs.TAG_NAME }}"
          git push origin main 
