name: goreleaser

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/accuknox/*
      GH_ACCESS_TOKEN: ${{ secrets.AK_PAT_REPO_SCOPE }}
      GIT_KEY: ${{ secrets.GIT_KEY }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Install Cosign
        uses: sigstore/cosign-installer@main

      - name: Setup access for private go modules
        env:
          GOPRIVATE: github.com/accuknox/*
          USER: accuknox-user
          TOKEN: ${{ secrets.AK_PAT_REPO_SCOPE }}
        run: |
          git config --global url."https://${USER}:${TOKEN}@github.com".insteadOf "https://github.com"
          

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}